name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Set up SSH
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ../solomon.pem
      - name: Change permission of SSH private key
        run: chmod 600 ../solomon.pem

      - name: SSH into EC2 instance and run commands
        uses: appleboy/ssh-action@master
        with:
          host: ec2-44-201-192-126.compute-1.amazonaws.com
          username: solohitech
          key: |
            ${{ file("../solomon.pem") }}
          script: |
            # Add your commands here
            # Example: cd /path/to/your/app && npm install && npm run build

      - name: Cleanup SSH private key
        run: rm ./solomon.pem
