name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Prepare deployment script
        run: |
          echo '#!/bin/bash' >> deploy.sh
          echo '# Add your deployment commands here' >> deploy.sh
          echo '# Example: rsync -avz ./dist user@server:/path/to/destination' >> deploy.sh
          chmod +x deploy.sh

      - name: Connect to EC2 instance and deploy application
        run: |
          ssh -i ../../solomon.pem solohitech@ec2-paris2IP-44.201.192.126 'bash -s' < deploy.sh
