name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: SSH into EC2 instance and deploy code
        uses: appleboy/ssh-action@master
        with:
          host: 44.201.192.126
          username: solohitech
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Copy the code to the remote server
            scp -r . solohitech@ec2-44-201-192-126.compute-1.amazonaws.com:/justin

            # SSH into the remote server and perform deployment steps
            ssh solohitech@ec2-44-201-192-126.compute-1.amazonaws.com "cd justin && npm install && npm run build && pm2 restart server.js"

          port: 22
          timeout: 50s
          command_timeout: 10m
          proxy_port: 22
          proxy_timeout: 50s
